package jp.megachips.frizzservice;

public class Frizz {
	
	protected Type     mType;
	
	/**
	 * @return generic type of this sensor.
     */
    public Type getType() {
    	return mType;
    }
    
    public enum PdrHolding {
    	STABLE,
    	FIX,
    	SWING,
    	WAIST,
    	AUTO,
    	WATCHING,
    }
    
	public enum Type {

	//This const uses batch mode when frizz's software fifo is empty.
	SENSOR_TYPE_FIFO_EMPTY,	// 0

	//These const are Android Senosr Type.
	SENSOR_TYPE_ACCELEROMETER,	// 1
	SENSOR_TYPE_MAGNETIC_FIELD,	// 2
	SENSOR_TYPE_ORIENTATION,	// 3
	SENSOR_TYPE_GYROSCOPE,		// 4
	SENSOR_TYPE_LIGHT,			// 5
	SENSOR_TYPE_PRESSURE,		// 6
	SENSOR_TYPE_TEMPERATURE,	// 7
	SENSOR_TYPE_PROXIMITY,		// 8
	SENSOR_TYPE_GRAVITY,		// 9
	SENSOR_TYPE_LINEAR_ACCELERATION,	// 10
	SENSOR_TYPE_ROTATION_VECTOR,		// 11
	SENSOR_TYPE_RELATIVE_HUMIDITY,		// 12
	SENSOR_TYPE_AMBIENT_TEMPERATURE,		// 13
	SENSOR_TYPE_MAGNETIC_FIELD_UNCALIBRATED,// 14
	SENSOR_TYPE_GAME_ROTATION_VECTOR,		// 15
	SENSOR_TYPE_GYROSCOPE_UNCALIBRATED,		// 16
	SENSOR_TYPE_SIGNIFICANT_MOTION,			// 17
	SENSOR_TYPE_STEP_DETECTOR,				// 18
	SENSOR_TYPE_STEP_COUNTER,				// 19
	SENSOR_TYPE_GEOMAGNETIC_ROTATION_VECTOR,// 20
	SENSOR_TYPE_HEART_RATE,				// 21
	SENSOR_TYPE_TILT_DETECTOR,			// 22

	//This const is MCC Sensor Type. (Extended Senosr)
	SENSOR_TYPE_MAGNET_RAW,		// 23
	SENSOR_TYPE_GYRO_RAW,		// 24
	SENSOR_TYPE_ACCEL_POWER,	// 25
	SENSOR_TYPE_ACCEL_LPF,		// 26
	SENSOR_TYPE_ACCEL_LINEAR,	// 27
	SENSOR_TYPE_MAGNET_PARAMETER,// 28
	SENSOR_TYPE_MAGNET_CALIB_SOFT,// 29
	SENSOR_TYPE_MAGNET_LPF,		// 30
	SENSOR_TYPE_GYRO_LPF,		// 31
	SENSOR_TYPE_DIRECTION,		// 32
	SENSOR_TYPE_POSTURE,		// 33
	SENSOR_TYPE_ROTATION_MATRIX,// 34
	SENSOR_TYPE_PDR,			// 35
	SENSOR_TYPE_VELOCITY,		// 36
	SENSOR_TYPE_RELATIVE_POSITION,// 37
	SENSOR_TYPE_CYCLIC_TIMER,	// 38
	SENSOR_TYPE_DEBUG_QUEUE_IN,// 39
	SENSOR_TYPE_ISP,			// 40
	SENSOR_TYPE_ACCEL_FALL_DOWN,// 41
	SENSOR_TYPE_ACCEL_POS_DET,	// 42
	SENSOR_TYPE_PDR_GEOFENCING,	// 43
	SENSOR_TYPE_GESTURE,  		// 44
	SENSOR_TYPE_MIGRATION_LENGTH,// 45
	SENSOR_TYPE_MAGNET_CALIB_RAW,// 46
	SENSOR_TYPE_BLOOD_PRESSURE, //47
	SENSOR_TYPE_PPG_RAW,		// 48
	SENSOR_TYPE_WEARING_DETECTOR,// 49
	SENSOR_TYPE_MOTION_DETECTOR,// 50
	SENSOR_TYPE_BLOOD_PRESSURE_LEARN,	// 51

	SENSOR_TYPE_STAIR_DETECTOR,	// 52
	SENSOR_TYPE_ACTIVITY_DETECTOR,// 53
	SENSOR_TYPE_MOTION_SENSING,// 54
	SENSOR_TYPE_CALORIE, 	// 55
	SENSOR_TYPE_BIKE_DETECTOR, // 56

	}
    
}
